# Rustfmt configuration for Autobahn project
# Formatting rules for consciousness framework code

# Edition and version
edition = "2021"
version = "Two"

# Line length and wrapping
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports
imports_granularity = "Crate"
imports_layout = "Vertical"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Functions and methods
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
indent_style = "Block"

# Structs and enums
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20
struct_lit_single_line = true

# Comments and documentation
comment_width = 80
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true

# Strings and arrays
string_lit_single_line = true
array_width = 60
chain_width = 60

# Spacing and alignment
spaces_around_ranges = false
type_punctuation_density = "Wide"
use_small_heuristics = "Default"

# Biological/scientific code formatting
where_single_line = false
force_explicit_abi = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true

# Error handling
use_try_shorthand = true
use_field_init_shorthand = true

# Module organization
module_separator = "\n"
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0

# Match expressions
match_block_trailing_comma = true
match_arm_blocks = true
match_arm_leading_pipes = "Never"

# Newlines
newline_style = "Unix"
trailing_comma = "Vertical"
trailing_semicolon = true

# Advanced formatting
condense_wildcard_suffixes = true
force_multiline_blocks = false
overflow_delimited_expr = true
struct_lit_width = 18
struct_variant_width = 35

# Consciousness framework specific
# Allow longer lines for mathematical expressions
# and biological process descriptions
single_line_if_else_max_width = 50
attr_fn_like_width = 70
closure_block_indent_threshold = 7 